name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_KEY }}" | docker login -u "${{ secrets.DOCKER_HUB_NAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_HUB_NAME }}/nginx-image-2:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_HUB_NAME }}/nginx-image-2:latest
